export default {
  SET_AUTH_STATE: 'SET_AUTH_STATE',
  AUTHENTICATING: 'AUTHENTICATING',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGIN_ERROR: 'LOGIN_ERROR',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  BEARER_TOKEN: 'BEARER_TOKEN',
  USER_NAME: 'USER_NAME'
};
