export default {
  SET_ORDER_STATE: 'SET_ORDER_STATE',
  ORDERS_FETCHING: 'ORDERS_FETCHING',
  ORDERS_FETCH_SUCCESS: 'ORDERS_FETCH_SUCCESS',
  ORDERS_FETCH_ERROR: 'ORDERS_FETCH_ERROR',
  SET_SINGLE_ORDER_STATE: 'SET_SINGLE_ORDER_STATE',
  SINGLE_ORDER_FETCHING: 'SINGLE_ORDER_FETCHING',
  SINGLE_ORDER_FETCH_SUCCESS: 'SINGLE_ORDER_FETCH_SUCCESS',
  SINGLE_ORDER_FETCH_ERROR: 'SINGLE_ORDER_FETCH_ERROR',
  SET_PAYMENT_STATE: 'SET_PAYMENT_STATE',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_PROCESS_SUCCESS: 'PAYMENT_PROCESS_SUCCESS',
  PAYMENT_PROCESS_ERROR: 'PAYMENT_PROCESS_ERROR',
  UPDATE_PAID_ORDER: 'UPDATE_PAID_ORDER'
};
