export default {
  SET_CART_FETCH_STATE: 'SET_CART_FETCH_STATE',
  CART_FETCHING: 'CART_FETCHING',
  CART_FETCH_SUCCESS: 'CART_FETCH_SUCCESS',
  SET_CART_ADD_STATE: 'SET_CART_ADD_STATE',
  CART_ADDING: 'CART_ADDING',
  CART_ADD_SUCCESS: 'CART_ADD_SUCCESS',
  CART_ID: 'CART_ID',
  SET_CART_UPDATE_STATE: 'SET_CART_UPDATE_STATE',
  CART_UPDATING: 'CART_UPDATING',
  CART_UPDATE_SUCCESS: 'CART_UPDATE_SUCCESS',
  CART_UPDATE_ERROR: 'CART_UPDATE_ERROR'
};
