export default {
  SIZE_S: 'SIZE_S',
  SIZE_M: 'SIZE_M',
  SIZE_L: 'SIZE_L',
  SIZE_XL: 'SIZE_XL',
  SIZE_XXL: 'SIZE_XXL',
  COLOR_WHITE: 'COLOR_WHITE',
  COLOR_BLACK: 'COLOR_BLACK',
  COLOR_RED: 'COLOR_RED',
  COLOR_ORANGE: 'COLOR_ORANGE',
  COLOR_YELLOW: 'COLOR_YELLOW',
  COLOR_GREEN: 'COLOR_GREEN',
  COLOR_BLUE: 'COLOR_BLUE',
  COLOR_INDIGO: 'COLOR_INDIGO',
  COLOR_PURPLE: 'COLOR_PURPLE',
  PRODUCT_FETCHING: 'PRODUCT_FETCHING',
  SET_PRODUCT_STATE: 'SET_PRODUCT_STATE',
  PRODUCT_FETCH_SUCCESS: 'PRODUCT_FETCH_SUCCESS'
};
