export default {
  PRODUCTS_STATE: 'PRODUCTS_STATE',
  SET_PRODUCTS_STATE: 'SET_PRODUCTS_STATE',
  SET_PRODUCTS: 'SET_PRODUCTS',
  POPULATE_PRODUCTS: 'POPULATE_PRODUCTS',
  FETCHING_PRODUCTS: 'FETCHING_PRODUCTS',
  PRODUCTS_FETCH_SUCCESS: 'PRODUCTS_FETCH_SUCCESS',
  PRODUCTS_FETCHING: 'PRODUCTS_FETCHING',
  PRODUCTS_FETCH_ERROR: 'PRODUCTS_FETCH_ERROR',
  DEFAULT_STATE: 'DEFAULT_STATE',
  DEFAULT_PRODUCTS_LIMIT: 6
};
